config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'
  get 'sessions/new'
  post 'sessions/create'

  get  '/signup',  to: 'customers#new'
  get  '/customer/signup',  to: 'customers#new'
  post  '/customer/signup',  to: 'customers#create'
  get  '/driver/signup',  to: 'drivers#new'
  post  '/driver/signup',  to: 'drivers#create'

  get    '/login',   to: 'sessions#new'
  get    '/driver/login',   to: 'sessions#new'
  post   '/driver/login',   to: 'sessions#create'
  get    '/customer/login',   to: 'sessions#new'
  post   '/customer/login',   to: 'sessions#create'

  delete '/logout',  to: 'sessions#destroy'

  get '/customers/:id/topup',  to: 'customers#topup', as: 'topup'
  patch '/customers/:id/topup',  to: 'customers#commit_topup', as: 'commit_topup'

  get '/drivers/:id/set_location',  to: 'drivers#set_location', as: 'set_location'
  patch '/drivers/:id/set_location',  to: 'drivers#commit_location', as: 'commit_location'

  get 'orders/confirm'

  get 'customers/:id/orders', to: 'customers#orders'
  get 'drivers/:id/orders', to: 'drivers#orders'

  get    '/orders/goride',   to: 'orders#goride'
  get    '/orders/gocar',   to: 'orders#gocar'
  post 'orders/check', to: 'orders#check', as: 'check_order'
  post 'orders/create', to: 'orders#create', as: 'place_order'


  resources :users
  resources :customers
  resources :drivers
  resources :orders

  # get '/users/:id/topup', to: 'users#topup', as: 'user_topup'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password

  before_save { email.downcase! }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 }, format:{ with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :phone, presence: true, numericality:true, length: { maximum: 15, minimum:6 }

  validates :password, presence: true, on: :create
  validates :password, length: { minimum: 6 }, allow_blank:true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]
  before_action :correct_user,   only: [:edit, :update]

  def index
    @users = User.paginate(page:params[:page])
    @users.per_page = 10
  end

  def new
    if logged_in?
      redirect_to current_user
    end
  @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Go-jek Web Services App"
      redirect_to @user
    else
      render 'new'
    end
  end

  def topup
    @user = User.find(params[:id])
  end

  def commit_topup
    @user = User.find(params[:id])
    if @user.update_attributes(gopay_params)
      flash[:success] = "Topup Success"
      redirect_to @user
    else
      render 'topup'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :phone, :password, :password_confirmation)
    end

    def gopay_params
      params.require(:user).permit(:gopay)
    end

    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless @user == current_user
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user, url: yield(:urls)) do |f| %>
  <%= render 'shared/error_messages' %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.text_field :email, class: 'form-control' %>

  <%= f.label :phone %>
  <%= f.text_field :phone, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation, "Confirmation" %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
  <tr>
    <td><%= user.id %></td>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.phone %></td>
    <td><%= user.gopay %></td>
    <td></td>
  </tr>

app/views/users/edit.html.erb
<% provide(:button_text, 'Update my Go-jek account') %>
<h1>Edit Profile</h1>
<p style="text-align: center
">Please Edit Your Profile</p>

<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/index.erb
<h1>Users List</h1>
<%= will_paginate %>
<table class="table">
  <tr>
    <td>id</td>
    <td>Name</td>
    <td>Email</td>
    <td>Phone</td>
    <td>Gopay</td>
    <td>Action</td>
  </tr>

  <%= render @users %>

</table>
<%= will_paginate %>

app/views/users/new.html.erb
<% type = request.fullpath.split('/').reject { |e| e.empty? }.first%>
<% url_form = type == 'driver' ? driver_signup_path : customer_signup_path %>

<% provide(:urls, url_form) %>
<% provide(:button_text, 'Create my Go-jek account') %>
<h1>Sign Up</h1>
<p style="text-align: center
">Please Sign up! Thank you..</p>

<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/orders.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<%= render '/orders/orders' %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<%= @user.email %>
<%= @user.phone %>