config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'
  get 'sessions/new'
  post 'sessions/create'

  get  '/signup',  to: 'customers#new'
  get  '/customer/signup',  to: 'customers#new'
  post  '/customer/signup',  to: 'customers#create'
  get  '/driver/signup',  to: 'drivers#new'
  post  '/driver/signup',  to: 'drivers#create'

  get    '/login',   to: 'sessions#new'
  get    '/driver/login',   to: 'sessions#new'
  post   '/driver/login',   to: 'sessions#create'
  get    '/customer/login',   to: 'sessions#new'
  post   '/customer/login',   to: 'sessions#create'

  delete '/logout',  to: 'sessions#destroy'

  get '/customers/:id/topup',  to: 'customers#topup', as: 'topup'
  patch '/customers/:id/topup',  to: 'customers#commit_topup', as: 'commit_topup'

  get '/drivers/:id/set_location',  to: 'drivers#set_location', as: 'set_location'
  patch '/drivers/:id/set_location',  to: 'drivers#commit_location', as: 'commit_location'

  get 'orders/confirm'

  get 'customers/:id/orders', to: 'customers#orders'
  get 'drivers/:id/orders', to: 'drivers#orders'

  get    '/orders/goride',   to: 'orders#goride'
  get    '/orders/gocar',   to: 'orders#gocar'
  post 'orders/check', to: 'orders#check', as: 'check_order'
  post 'orders/create', to: 'orders#create', as: 'place_order'


  resources :users
  resources :customers
  resources :drivers
  resources :orders

  # get '/users/:id/topup', to: 'users#topup', as: 'user_topup'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  belongs_to :driver, optional: true

  before_save :calculate_total, :distance_matrix

  enum service: {
    "goride" => 0,
    "gocar" => 1
  }

  enum payment: {
    "cash" => 0,
    "gopay" => 1
  }

  validates_with OrderLocationValidator
  validates_with GopayValidator
  validates :payment, inclusion: payments.keys
  validates :service, inclusion: services.keys
  validates :pickup, :destination, :payment, presence:true

  def api_key
    api = 'AIzaSyAT3fcxh_TKujSW6d6fP9cUtrexk0eEvAE'
  end

  def get_google_api
    matrix = []
    gmaps = GoogleMapsService::Client.new(key: api_key)
    origins = pickup
    destinations = destination
    if !origins.empty? && !destinations.empty?
      matrix = gmaps.distance_matrix(origins, destinations, mode: 'driving', language: 'en-AU', avoid: 'tolls')
    end
    matrix
  end

  def pickup_address
    result = []
    if api_not_empty?
      result = get_google_api[:origin_addresses]
      result.reject! { |address| address.empty? }
    end
    result
  end

  def destination_address
    result = []
    if api_not_empty?
      result = get_google_api[:destination_addresses]
      result.reject! { |address| address.empty? }
    end
    result
  end

  def distance_matrix
    result = 0
    if api_not_empty?
      if get_google_api[:rows][0][:elements][0][:status] == "OK"
        result = get_google_api[:rows][0][:elements][0][:distance][:value]
        result = (result.to_f / 1000).round(2)
        result = 1.0 if result < 1.0
      end
    end
    self.distance = result
  end

  def cost_per_km
    service == 'gocar' ? 2500 : 1500
  end

  def calculate_total
    total = 0
    if api_not_empty?
      total = distance_matrix * cost_per_km
    end
    self.total = total
  end

  def gopay_sufficient?
    result = false
    if api_not_empty?
      result = true if customer.gopay >= calculate_total
    end
    result
  end

  def api_not_empty?
    !get_google_api.empty?
  end

  def nearest_driver
    pickup_location = Location.get_location(pickup)
    customer_destination = Location.get_location(destination)
    drivers = Driver.where(area_id: pickup_location.area_id)
    origin_coordinate = eval(pickup_location.coordinate)

    drivers_dist = drivers.reduce(Hash.new) do |hash, driver|
      hash[driver.name] = Location.distance(origin_coordinate, driver.coordinate)
      hash
    end
    drivers_dist.min_by { |driver, length| length }
  end

  def nearest_all_drivers
    pickup_location = Location.get_location(pickup)
    customer_destination = Location.get_location(destination)
    drivers = Driver.all
    origin_coordinate = eval(pickup_location.coordinate)

    drivers_dist = drivers.reduce(Hash.new) do |hash, driver|
      hash[driver.name] = Location.distance(origin_coordinate, driver.coordinate)
      hash
    end

    drivers_dist.min_by { |driver, length| length }

  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show]

  def index
    @orders = Order.all
  end

  def show
  end

  def new
    @order = Order.new
  end

  def gocar
    @order = Order.new
  end

  def goride
    @order = Order.new
  end

  def check
    @order = Order.new(order_params)
    @order.customer_id = session[:user_id]
    respond_to do |format|
      if @order.valid?
        format.html{render :confirm}
      else
        if @order.service == 'gocar'
          format.html{render :gocar}
        else
          format.html{render :goride}
        end
      end
    end
  end

  def confirm
    @order = Order.new(order_params)
  end

  def create
    @order = Order.new(order_params)

    @order.customer_id = session[:user_id]
    respond_to do |format|
      if @order.save
        format.html{ redirect_to @order}
      else
        format.html{render :new}
      end
    end
  end

  private

  def set_order
    @order = Order.find(params[:id])
  end

  def order_params
    params.require(:order).permit(:pickup, :destination, :payment, :distance, :service, :total)
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_error_messages.html.erb
<% if @order.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@order.errors.count, "error") %>.
    </div>
    <ul>
    <% @order.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/orders/_form.html.erb
<%= form_for(@order, url:check_order_path) do |f| %>
    <%= render 'error_messages' %>

    <%= f.label :pickup %>
    <%= f.text_field :pickup, class: 'form-control' %>

    <%= f.label :destination %>
    <%= f.text_field :destination, class: 'form-control' %>

    <%= f.hidden_field :service, value:yield(:service_type) %>
    <%= f.hidden_field :payment, value:'cash' %>


    <%= f.submit yield(:button_text), class: "btn btn-primary" %>
  <% end %>

app/views/orders/_orders.html.erb
<table class="table">
  <tr>
    <td>Id</td>
    <td>Pickup</td>
    <td>Destination</td>
    <td>Payment</td>
    <td>Distance</td>
    <td>Total</td>
    <td>Customer</td>
    <td>Driver</td>
    <td>Action</td>
  </tr>

  <% @orders.each do|o| %>
  <tr class="<%= cycle('list_line_odd','list_line_even')%>">
    <td><%= o.id %></td>
    <td><%= o.pickup %></td>
    <td><%= o.destination %></td>
    <td><%= o.payment %></td>
    <td><%= o.distance %></td>
    <td><%= number_to_currency(o.total, unit: "Rp ", delimiter: ".", separator: ",")  %></td>
    <td><%= o.customer.name %></td>
    <td></td>
    <td>  <%= link_to 'Show', o %>
          <%= link_to 'Edit', edit_order_path(o) %>
          <%= link_to 'Destroy', o, method: :delete, data: { confirm: 'Are you sure?' } %>
    </td>
  </tr>
  <% end %>
</table>

app/views/orders/confirm.html.erb
<% provide(:button_text, 'Place Order') %>
<h1>Confirm Order</h1>
<p style="text-align: center
">Please ensure input the details below..</p>


<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
  <%= form_for(@order, url:place_order_path) do |f| %>
    <%= render 'error_messages' %>

    <%= f.label :pickup %>
    <%= f.text_field :pickup, readonly: true, class: 'form-control' %>

    <%= f.label :destination %>
    <%= f.text_field :destination, readonly: true, class: 'form-control' %>

    <%= f.hidden_field :service, value: @order.service %>

    <table class="table">
      <tr>
        <td>Service </td>
        <td><%= @order.service.upcase  %></td>
      </tr>

      <tr>
        <td>Distance</td>
        <td><%= @order.distance_matrix  %> Km</td>
      </tr>

      <tr>
        <td>Total Cost</td>
        <td><%= number_to_currency(@order.distance_matrix * @order.cost_per_km, unit: "Rp ", delimiter: ".", separator: ",") %></td>
      </tr>

      <tr>
        <td>Please Choose Your Payment</td>
        <td>
          <% if @order.gopay_sufficient? %>
            <div class="radio">
              <label>
                <%= f.radio_button :payment, 'cash'%>
                CASH
              </label>
            </div>
            <div class="radio">
              <label>
                <%= f.radio_button :payment, 'gopay', :checked => true %>
                GOPAY
              </label>
            </div>
            your gopay credit : <%= number_to_currency(@order.customer.gopay, unit: "Rp ", delimiter: ".", separator: ",")  %>
          <% else %>
            <div class="radio">
              <label>
                <%= f.radio_button :payment, 'cash', :checked => true%>
                CASH
              </label>
            </div>
            <div class="radio">
              <label>
                <%= f.radio_button :payment, 'gopay', disabled: true %>
                GOPAY
              </label>
            </div>
            your gopay credit is not sufficient: <%= number_to_currency(@order.customer.gopay, unit: "Rp ", delimiter: ".", separator: ",")  %>

          <% end %>
        </td>
      <tr>

    </table>

    <%= f.submit yield(:button_text), class: "btn btn-primary" %>
  <% end %>
  </div>
</div>

app/views/orders/gocar.html.erb
<% provide(:button_text, 'Order GOCAR') %>
<% provide(:service_type, "gocar") %>
<h1>Order Go Car</h1>
<p style="text-align: center">Please input the details below..</p>
<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/orders/goride.html.erb
<% provide(:button_text, 'Order GORIDE') %>
<% provide(:service_type, "goride") %>
<h1>Order Go Ride</h1>
<p style="text-align: center">Please input the details below..</p>
<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<%= render 'orders/orders' %>

app/views/orders/new.html.erb
<% provide(:button_text, 'Place Order') %>
<% provide(:service_type, 'goride') %>
<h1>Order Go Ride</h1>
<p style="text-align: center">Please input the details below..</p>
<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
  <h2>Your Order is Succeed</h2>
  <h3>Please wait, We're searching a driver for you</h3>


  <table class="table">

    <tr>
      <td>Service</td>
      <td><%= @order.service.upcase %></td>
    </tr>

    <tr>
      <td>Pickup Location</td>
      <td><%= @order.pickup %></td>
    </tr>

    <tr>
      <td>Pickup Location</td>
      <td><%= @order.destination %></td>
    </tr>

    <tr>
      <td>Distance</td>
      <td><%= @order.distance %> Km</td>
    </tr>

    <tr>
      <td>Payment Type</td>
      <td><%= @order.payment.upcase %></td>
    </tr>


    <tr>
      <td>Total Cost</td>
      <td><%= number_to_currency(@order.total, unit: "Rp ", delimiter: ".", separator: ",")  %></td>
    </tr>


  </table>



<%= link_to 'Back', customer_path(id: @order.customer_id) %>